# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5708cd5eb859411160052acaa91397428ded43dc78053f8550cd3f1f8ffb436359243ff92c0abf1438de09ea26bde5e6e5daa3bc6fcc6f66c2cae775595da51b

test:
  secret_key_base: b61bd6c61797c92d059613bb879d4a22b06e8d8cd9f71a49309c4930eb23b8783d8c442a8abdabcce78b00e46a638a1e521db9d99068d62c0b6e7dbb0d6fe83e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
